### ISSUE TITLE
Restoring a Unix Backup on Windows is not working well

### ISSUE THREAD

**Issue by nagyesta** [nagyesta/file-barj#94]
### Background

Restoring a Unix Backup on Windows is not working well due to the following factors:

1. If the path of two files differs only in case (as Unix is case sensitive) there is a collision on Windows (where the file names are case in-sensitive).
2. The POSIX permissions will not be restored properly. Due to this, a long list of errors will list all files at the end as not fully restored
3. The restore path transformation logic assumes that there is a drive letter on the source path side (although there was none in case of the original Unix backup where each path starts with /) (Solved by #127)

### Done criteria

- [x] Case sensitivity issues are reported (errors avoided)
- [x] POSIX permission errors are listed in a user-friendly format
- [x] Allow setting new command line option to ignore permission and owner/group differences during checks
- [x] Tests are updated
- [x] Documentation is updated

**Comment by nagyesta** [comment]
### New symptoms

Error when restoring link pointing to external file which does not exist:

```
20:59:46.291 [main] ERROR c.github.nagyesta.filebarj.job.Main - Execution failed:
com.github.nagyesta.filebarj.core.backup.ArchivalException: Failed to create symbolic link: ...\assumed-identity\venv\bin\python pointing to: \usr\bin\python3.10
        at com.github.nagyesta.filebarj.core.restore.pipeline.RestorePipeline.lambda$createSymbolicLinks$38(RestorePipeline.java:545)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.concurrent.ConcurrentHashMap$EntrySpliterator.forEachRemaining(ConcurrentHashMap.java:3652)
Caused by: java.nio.file.FileSystemException: ...\assumed-identity\venv\bin\python: A required privilege is not held by the client
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
```

Files are still marked as changed metadata after the restore probably due to two fators:

1. File metadata contains the time-stamps as well
2. Since the time stamps do not match, the restore of the full metadata is attempted (which includes permission restore as well, but it will most likely fail)

### Done criteria

- [ ] Investigated and fixed change detection/metadata restore issue
- [ ] External link creation does not stop the restore (although it will show up in the end as difference)

**Comment by nagyesta** [comment]
The previous fix was not successful.
